language: java

install: echo "I don't trust Maven. Gradle FTW!"

jdk:
  - oraclejdk6

notifications:
  hipchat:
    rooms:
      48205_324138@48205_mr._build
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Changes</a>)'
    format: html
  email:
    - giancarlo.pace@jobrapido.com
    - michele.cantelli@jobrapido.com

branches:
  only:
    - master
    - /^feature-.*$/
